//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class EffectData_Container : UnityEngine.ScriptableObject
{
    
    private static EffectData_Container _instance;
    
    public List<EffectData> listData;
    
    public Dictionary<EEffectName, EffectData> mapData_Key_Is_eEffectName;
    
    public static EffectData_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(EffectData_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((EffectData)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Key_Is_eEffectName();
    }
    
    private void Init_mapData_Key_Is_eEffectName()
    {
        this.mapData_Key_Is_eEffectName = listData.ToDictionary(x => x.eEffectName);
    }
}

public enum EEffectName
{
    
    Default_Damage,
    
    Summon_Fairy_Damage,
}

#region 
static
public class EffectData_ContainerHelper
{
    
    public static EffectData GetEffectData(this EEffectName eKey, System.Action<string> OnError = null)
    {
          EffectData pData;
          if(EffectData_Container.instance.mapData_Key_Is_eEffectName.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(EffectData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
