//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;



public class EnemyData : UnityEngine.ScriptableObject
{
    
    public string strEnemyName;
    
    public float fHP;
    
    public float fMoveSpeed;
    
    public float fColliderPosY;
    
    public float fCrashDamage;
    
    public float fColliderRadius;
    
    public int iAppearWave;
    
    public float fGetMP;
    
    public string strSpritePath;
    
    /// <summary>
    /// 자동으로 할당되는 필드입니다. 의존되는 필드 : <see cref="strEnemyName"/>
    /// </summary>
    public EEnemyType eEnemyType;
    
    /// <summary>
    /// 자동으로 할당되는 필드입니다. 의존되는 필드 : <see cref="strSpritePath"/>
    /// </summary>
    public UnityEngine.Sprite pFile;
}
