//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class ManaPotionData_Container : UnityEngine.ScriptableObject
{
    
    private static ManaPotionData_Container _instance;
    
    public List<ManaPotionData> listData;
    
    public Dictionary<EManaPotion, ManaPotionData> mapData_Key_Is_eManaPotion;
    
    public static ManaPotionData_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(ManaPotionData_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((ManaPotionData)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Key_Is_eManaPotion();
    }
    
    private void Init_mapData_Key_Is_eManaPotion()
    {
        this.mapData_Key_Is_eManaPotion = listData.ToDictionary(x => x.eManaPotion);
    }
}

public enum EManaPotion
{
    
    Potion_0,
    
    Potion_1,
    
    Potion_2,
    
    Potion_3,
}

#region 
static
public class ManaPotionData_ContainerHelper
{
    
    public static ManaPotionData GetManaPotionData(this EManaPotion eKey, System.Action<string> OnError = null)
    {
          ManaPotionData pData;
          if(ManaPotionData_Container.instance.mapData_Key_Is_eManaPotion.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(ManaPotionData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
